<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click on first element abcd</name>
   <tag></tag>
   <elementGuidId>8bdbb5d5-1933-4b77-819b-c8ec99f1c948</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_here</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Roboto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>FONT.textFontFamily(font.family)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>abcd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentView&quot;)/div[@class=&quot;polyv-create-wrap desk_view ng-scope&quot;]/div[@class=&quot;polyv-items-wrap&quot;]/div[@class=&quot;polyv-items-inner&quot;]/div[@class=&quot;polyv-items-tab ng-isolate-scope&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/div[@class=&quot;other-items ng-scope&quot;]/div[@class=&quot;default-items ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;input-textbox&quot;]/div[@class=&quot;fonts_now&quot;]/ul[@class=&quot;ng-scope&quot;]/li[@class=&quot;fonts_now_li ng-scope&quot;]/span[@class=&quot;text_here&quot;]</value>
   </webElementProperties>
</WebElementEntity>
